[package]
name = "flatpak-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
env_logger = "0.11.8"
iced = { version = "0.13.1", features = ["tokio"] }
log = "0.4.27"
openssh = "0.11.5"
tokio = { version = "1.45.0", features = ["full"] }
